# docker-compose.yml
version: '3'

services:
  db:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_virtual_agent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
