apiVersion: v1
kind: Secret
metadata:
  name: ai-virtual-agent-proxy
  labels:
    {{- include "ai-virtual-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  session_secret: {{ .Values.sessionSecret.value | default (randAlphaNum 32) | quote }}
